FROM node:18-alpine

RUN \ 
  apk update && \
  apk add --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing&& \
  npm install -g typescript && \
  npm install -g ts-node \
  npm install
WORKDIR /app

COPY . .

EXPOSE 3000

CMD [ "npm", "run", "dev" ]